### PR TITLE
Added a lot of visual and features improvement

### PR DESCRIPTION
**Pull request by holyCowMp3**
- dark, light theme
- increased accesibility
- reimplemented and impoved UI side
- little bug fixes
- added Russian locale, Ukrainian WIP
Started devoping Balena api proxy container, for avoiding self-signed cert reliability issue. Will publish link for docker container soon :)

### CODE REVIEW

**Comment by Razikus** [comment]
Hey i will test it and merge after. 
Looks great!

About proxy container:
Our company recently created one great (imo) solution to handle this
I don't have time now to "extract" it into separate customizable thing, but may be really helpful

Check this out if you are working on it
https://github.com/scribe-systems-sp/open-balena-tunneler/tree/new-tunel-implementation/newTunnel

It uses only one container, redis and works really fast 
It's also scallable

It's not user-deploy-friendly, but for sure you can extract something from it

**Comment by markFieldman** [comment]
> Hey i will test it and merge after. 
> Looks great!
> 
> About proxy container:
> Our company recently created one great (imo) solution to handle this
> I don't have time now to "extract" it into separate customizable thing, but may be really helpful
> 
> Check this out if you are working on it
> https://github.com/scribe-systems-sp/open-balena-tunneler/tree/new-tunel-implementation/newTunnel
> 
> It uses only one container, redis and works really fast 
> It's also scallable
> 
> It's not user-deploy-friendly, but for sure you can extract something from it
> 

Thanks, for link. My opinion is making something easy to deploy, so using the simple way i will create standalone and customisable container for using for your own purpose

**Comment by Razikus** [comment]
Hello, can we somehow get in-touch on some "faster" communication system?
I have a little problem with merge this
Do you have discord for example?


I wrote to your e-mail but without answer

**Comment by markFieldman** [comment]
> Hello, can we somehow get in-touch on some "faster" communication system?
> I have a little problem with merge this
> Do you have discord for example?
> 
> 
> I wrote to your e-mail but without answer

Telegram @markfieldman
Mail - cto@solar-control.tech
Discord teslov#6328

**Comment by markFieldman** [comment]
Any updates, @Razikus?

**Comment by Razikus** [comment]
Merged after few fixes + consultation

**Comment by Razikus** [comment]
https://www.youtube.com/watch?v=7lsdJDiJ0QE

**Pull request merged**
